#############################################
# Menu advanced
#############################################

[[advanced]]
  name = "Overview"
  weight = 10
  identifier = "overview"
  url = "/advanced/overview/"

[[advanced]]
  name = "Specifications"
  weight = 20
  identifier = "specifications"
  url = "/advanced/specifications/"

[[advanced]]
  name = "Safety First"
  weight = 30
  identifier = "safety"
  url = "/safety/correct-use/"

[[advanced]]
  name = "Reachy's software"
  weight = 40
  identifier = "software"
  url = "/advanced/software/"

[[advanced]]
  name = "Services"
  weight = 50
  identifier = "services"
  url = "/advanced/services/"

#############################################
# Menu docs
#############################################

##################
## Getting started section
##################

[[docs]]
  name = "Getting started"
  weight = 10
  identifier = "docs-getting-started"

[[docs]]
  name = "Assemble mobile base + Reachy"
  weight = 100
  parent = "docs-getting-started"
  url = "/docs/getting-started/mobile-base/"

[[docs]]
  name = "Attach your robot without a mobile base"
  weight = 110
  parent = "docs-getting-started"
  url = "/docs/getting-started/attach/"

[[docs]]
  name = "Turn on your robot"
  weight = 120
  parent = "docs-getting-started"
  url = "/docs/getting-started/turn-on/"

[[docs]]
  name = "Connect to the dashboard"
  weight = 130
  parent = "docs-getting-started"
  url = "/docs/getting-started/dashboard/"

[[docs]]
  name = "Connect to your robot"
  weight = 140
  parent = "docs-getting-started"
  url = "/docs/getting-started/connect/"

[[docs]]
  name = "Connect your robot to the network"
  weight = 150
  parent = "docs-getting-started"
  url = "/docs/getting-started/network/"

##################
## Installation section
##################

[[docs]]
  name = "What needs to be installed"
  weight = 20
  identifier = "docs-installation"

[[docs]]
  name = "What needs to be installed"
  weight = 200
  parent = "docs-installation"
  url = "/docs/installation/full-installation-process/"

[[docs]]
  name = "Use Reachy SDK"
  weight = 210
  parent = "docs-installation"
  url = "/docs/installation/use-sdk/"

[[docs]]
  name = "Use VR teleoperation app"
  weight = 220
  parent = "docs-installation"
  url = "/docs/installation/use-vr/"

##################
## Update section
##################

[[docs]]
  name = "Update Reachy"
  weight = 30
  identifier = "docs-update"

[[docs]]
  name = "Update packages"
  weight = 300
  url = "/docs/update/"
  parent = "docs-update"

##################
## Support section
##################

[[docs]]
  name = "I have a problem!"
  weight = 40
  identifier = "docs-problem"

[[docs]]
  name = "Support"
  weight = 400
  url = "/docs/debug/support/"
  parent = "docs-problem"


#############################################
# Menu dashboard
#############################################

#######################
## Introduction section
#######################

[[dashboard]]
  name = "Introduction"
  weight = 10
  identifier = "dashboard-introduction"

[[dashboard]]
  name = "What is the dashboard?"
  weight = 100
  parent = "dashboard-introduction"
  url = "/dashboard/introduction/introduction/"

[[dashboard]]
  name = "First connection"
  weight = 110
  parent = "dashboard-introduction"
  url = "/dashboard/introduction/first-connection/"

#######################
## Content section
#######################

[[dashboard]]
  name = "Content"
  weight = 20
  identifier = "dashboard-content"

[[dashboard]]
  name = "Debug"
  weight = 200
  parent = "dashboard-content"
  url = "/dashboard/content/debug/"

[[dashboard]]
  name = "Dashboard"
  weight = 210
  parent = "dashboard-content"
  url = "/dashboard/content/dashboard/"

[[dashboard]]
  name = "Wifi"
  weight = 200
  parent = "dashboard-content"
  url = "/dashboard/content/wifi/"

[[dashboard]]
  name = "Services"
  weight = 230
  parent = "dashboard-content"
  url = "/dashboard/content/services/"

[[dashboard]]
  name = "Applications"
  weight = 240
  parent = "dashboard-content"
  url = "/dashboard/content/applications/"

#######################
## Installation section
#######################

[[dashboard]]
  name = "Installation"
  weight = 30
  identifier = "dashboard-installation"

[[dashboard]]
  name = "Software installation"
  weight = 300
  parent = "dashboard-installation"
  url = "/dashboard/installation/software/"

[[dashboard]]
  name = "Hardware to display Reachy's IP address"
  weight = 310
  parent = "dashboard-installation"
  url = "/dashboard/installation/hardware/"

#############################################
# Menu SDK
#############################################

##################
## Getting started section
##################

[[sdk]]
  name = "Getting Started"
  weight = 10
  identifier = "sdk-getting-started"

[[sdk]]
  name = "Introduction"
  weight = 100
  parent = "sdk-getting-started"
  url = "/sdk/getting-started/introduction"

[[sdk]]
  name = "Installation"
  weight = 110
  parent = "sdk-getting-started"
  url = "/sdk/getting-started/install"

[[sdk]]
  name = "Finding Reachy's IP"
  weight = 120
  parent = "sdk-getting-started"
  url = "/sdk/getting-started/finding-ip"

[[sdk]]
  name = "Hello World"
  weight = 130
  parent = "sdk-getting-started"
  url = "/sdk/getting-started/hello-world"

##################
## First moves section
##################

[[sdk]]
  name = "First moves"
  weight = 20
  identifier = "sdk-first-moves"

[[sdk]]
  name = "Once you're connected"
  weight = 200
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/intro"

[[sdk]]
  name = "Safety first"
  weight = 210
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/safety"

[[sdk]]
  name = "Arms kinematics"
  weight = 220
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/kinematics"

[[sdk]]
  name = "Controlling the arm"
  weight = 230
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/arm"

[[sdk]]
  name = "Record and play trajectories"
  weight = 240
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/record"

[[sdk]]
  name = "Controlling the head"
  weight = 250
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/head"

[[sdk]]
  name = "Reachy's cameras"
  weight = 260
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/cameras"

[[sdk]]
  name = "Controlling the fans"
  weight = 270
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/fans"

##################
## Mobile base section
##################

[[sdk]]
  name = "Mobile base"
  weight = 30
  identifier = "sdk-mobile-base"

[[sdk]]
  name = "Getting started with the mobile base"
  weight = 300
  parent = "sdk-mobile-base"
  url = "/sdk/mobile-base/getting-started"

[[sdk]]
  name = "Moving the mobile base"
  weight = 310
  parent = "sdk-mobile-base"
  url = "/sdk/mobile-base/moving-the-base"

[[sdk]]
  name = "Advanced"
  weight = 320
  parent = "sdk-mobile-base"
  url = "/sdk/mobile-base/drive-control-modes"

[[sdk]]
  name = "Anti-collision safety"
  weight = 330
  parent = "sdk-mobile-base"
  url = "/sdk/mobile-base/safety"

[[sdk]]
  name = "Using the mobile base without Reachy"
  weight = 340
  parent = "sdk-mobile-base"
  url = "/sdk/mobile-base/mobile-base-alone"

##################
## Application section
##################

[[sdk]]
  name = "Application"
  weight = 40
  identifier = "sdk-application"

[[sdk]]
  name = "Idle"
  weight = 400
  parent = "sdk-application"
  url = "/sdk/application/idle"

[[sdk]]
  name = "Face tracking"
  weight = 410
  parent = "sdk-application"
  url = "/sdk/application/face-tracking"

##################
## Appendix section
##################

[[sdk]]
  name = "Appendix"
  weight = 50
  identifier = "sdk-appendix"

[[sdk]]
  name = "APIs"
  weight = 500
  parent = "sdk-appendix"
  url = "/sdk/appendix/apis"

[[sdk]]
  name = "Support"
  weight = 510
  parent = "sdk-appendix"
  url = "/sdk/appendix/support"

#############################################
# Menu main - add parts to main page nav menu here!
#############################################

[[main]]
  name = "Description"
  url = "/advanced/overview/full-kit/"
  weight = 10

[[main]]
  name = "Setup Reachy"
  url = "/docs/getting-started/mobile-base/"
  weight = 20

[[main]]
  name = "Python SDK"
  url = "/sdk/getting-started/introduction/"
  weight = 30

[[main]]
  name = "VR"
  weight = 40
  url = "/vr/introduction/introduction/"

[[main]]
  name = "Dashboard"
  weight = 50
  url = "/dashboard/introduction/introduction/"

[[main]]
  name = "Help"
  weight = 60
  url = "/help/debug/check-dashboard/"

#############################################
# Menu VR
#############################################

##################
## Intro section
##################

[[vr]]
  name = "Introduction"
  weight = 10
  identifier = "vr-introduction"

[[vr]]
  name = "Introduction"
  weight = 100
  parent = "vr-introduction"
  url = "vr/introduction/introduction"

##################
## Compatibility section
##################

[[vr]]
  name = "Compatibility"
  weight = 20
  identifier = "vr-compatibility"

[[vr]]
  name = "Compatible headsets"
  weight = 200
  parent = "vr-compatibility"
  url = "vr/compatibility/headsets"

[[vr]]
  name = "PC requirements"
  weight = 210
  parent = "vr-compatibility"
  url = "vr/compatibility/pc-requirements"

##################
## Installation section
##################

[[vr]]
  name = "VR Installation"
  weight = 30
  identifier = "vr-installation"

[[vr]]
  name = "What needs to be installed"
  weight = 300
  parent = "vr-installation"
  url = "vr/installation/installation"

##################
## Using section
##################

[[vr]]
  name = "Using the app"
  weight = 40
  identifier = "vr-use"

[[vr]]
  name = "🚨 Best practice"
  weight = 400
  parent = "vr-use"
  url = "vr/use-teleop/best-practice"

[[vr]]
  name = "Controllers inputs"
  weight = 410
  parent = "vr-use"
  url = "vr/use-teleop/commands"

[[vr]]
  name = "Set Reachy ready"
  weight = 420
  parent = "vr-use"
  url = "vr/use-teleop/prepare-robot"

[[vr]]
  name = "Teleoperate Reachy"
  weight = 430
  parent = "vr-use"
  url = "vr/use-teleop/start"

[[vr]]
  name = "Teleoperation messages"
  weight = 440
  parent = "vr-use"
  url = "vr/use-teleop/messages"

##################
## Problem section
##################

[[vr]]
  name = "Problem"
  weight = 50
  identifier = "vr-problem"

[[vr]]
  name = "Debug"
  weight = 500
  parent = "vr-problem"
  url = "vr/problem/debug"

[[vr]]
  name = "Support"
  weight = 510
  parent = "vr-problem"
  url = "vr/problem/support-vr"

#############################################
# Menu help
#############################################

################
## Debug Section
################

[[help]]
  name = "Debug"
  weight = 10
  identifier = "help-debug"

[[help]]
  name = "Check the dashboard"
  weight = 100
  parent="help-debug"
  url = "/help/debug/check-dashboard/"

[[help]]
  name = "Quick debug with the Python SDK"
  weight = 110
  parent="help-debug"
  url = "/help/debug/python-sdk-error/"

[[help]]
  name = "FAQ"
  weight = 120
  parent="help-debug"
  url = "/help/debug/faq/"

[[help]]
  name = "Support"
  weight = 130
  parent="help-debug"
  url = "/help/debug/support/"

#################
## System section
#################

[[help]]
  name = "System"
  weight = 20
  identifier = "help-system"

[[help]]
  name = "Finding Reachy's IP"
  weight = 200
  parent="help-system"
  url = "/help/system/find-my-ip/"

[[help]]
  name = "Check which motors are connected"
  weight = 210
  parent="help-system"
  url = "/help/system/discovery-tool/"

#################
## Safety section
#################

[[help]]
  name = "Safety"
  weight = 30
  identifier = "help-safety"

[[help]]
  name = "Use Reachy properly"
  weight = 300
  parent="help-safety"
  url = "/help/safety/correct-use/"

[[help]]
  name = "Use VR teleoperation"
  weight = 310
  parent="help-safety"
  url = "/help/safety/vr-use/"

#############################################
[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/pollenrobotics"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/pollen-robotics/"
  post = "v0.1.0"
  weight = 20


